// TCF EE Studio X - Subject Bank (Writing Prompts)
// Complete data for juin-2026, mai-2026, avril-2026

const DEFAULT_SUBJECT_BANK = {
  "juin-2026": [
    {
      num: 1,
      t1: { consigne: "Vous avez vu une annonce en ligne offrant de l'aide aux personnes qui veulent apprendre le français, en les mettant en contact avec des partenaires pour pratiquer et améliorer leur niveau. Vous rédigez un courriel pour répondre, en vous présentant et en disant pourquoi vous voulez pratiquer le français." },
      t2: { consigne: "Vous avez assisté à une fête de famille. Vous envoyez un message à vos amis pour leur parler de cette fête et expliquer ce que vous avez préféré." },
      t3: { titre: "Villes sans voitures : avantages et précautions", doc1: "En raison de la pollution importante observée dans de nombreuses régions, certaines villes ont choisi d'interdire les voitures dans les zones urbaines. La ville d'Oslo, en Norvège, a appliqué cette mesure récemment et constate des effets positifs pour tous. Avec le temps, les accidents diminuent, la dépendance au pétrole est réduite et l'air devient plus sain.", doc2: "Beaucoup de villes lancent des projets visant à interdire la circulation automobile en centre-ville sans préparer les infrastructures indispensables. Certes, diminuer le trafic permettrait de réduire les bouchons, le stress et la pollution de l'air. Mais il est également important de prévoir de grands parkings, de renforcer les transports publics, et de donner des autorisations particulières à certains professionnels, comme les services d'urgence, la police ou les livreurs." }
    },
    {
      num: 2,
      t1: { consigne: "Un de vos proches souhaite partir en voyage pour découvrir un nouveau pays. Vous lui envoyez un message pour lui présenter votre pays et ses traditions (lieux à visiter, sites touristiques, monuments, etc.)." },
      t2: { consigne: "Vous avez commencé un nouvel emploi. Vous envoyez un courriel à vos proches pour leur raconter votre première semaine (entreprise, poste, missions, etc.)." },
      t3: { titre: "Femmes et hommes au travail", doc1: "Dans certaines régions, comme le Québec, l'égalité entre les femmes et les hommes est une réalité. Beaucoup de femmes occupent désormais des postes à responsabilité et travaillent dans des domaines traditionnellement masculins, tels que le bâtiment ou la gestion d'entreprise. Avec les lois sur l'égalité et le changement des mentalités, les femmes ont aujourd'hui accès aux mêmes métiers que les hommes, sans subir de discrimination.", doc2: "Même si des efforts sont faits pour atteindre la parité, des inégalités demeurent. Par exemple, certains métiers sont encore très féminisés, comme celui de sage-femme ou d'assistante maternelle. De plus, certaines personnes estiment que les femmes doivent rester à la maison pour s'occuper des enfants plutôt que travailler dans des métiers exigeants ou à responsabilité. Il reste donc beaucoup à faire pour changer les mentalités et garantir les mêmes chances aux femmes et aux hommes." }
    },
    {
      num: 3,
      t1: { consigne: "Vous rédigez un message à vos amis pour les convier à une fête d'anniversaire surprise organisée pour votre meilleur(e) ami(e). Indiquez le lieu, la date et l'heure, etc." },
      t2: { consigne: "Vous avez pris part à un marché d'occasion dans votre ville. Rédigez un article sur votre blog pour raconter cette activité et dire pourquoi elle vous a plu." },
      t3: { titre: "Les vols low-cost : avantages et limites", doc1: "Je voyage souvent avec des compagnies aériennes à petit prix. Les compagnies low-cost proposent des billets beaucoup moins chers que les compagnies classiques. Parfois, cela me revient même moins cher que de voyager en voiture ou en train. Mais avec ces tarifs très bas, il y a forcément un inconvénient : aucun service n'est inclus à bord (pas de repas ni de boissons). À mon avis, ce type de vol n'est donc pas adapté aux longs trajets.", doc2: "Dernièrement, j'ai décidé d'arrêter de voyager avec les compagnies aériennes low-cost. Après mûre réflexion, ce choix m'a paru évident : les sièges sont inconfortables, les employés travaillent dans des conditions difficiles et les avions semblent parfois trop vieux pour garantir une bonne sécurité. Désormais, pour mes déplacements, je préfère utiliser la voiture ou le train, qui permet d'admirer de beaux paysages. Pour les longs trajets, je choisirai plutôt une compagnie aérienne classique." }
    },
    {
      num: 4,
      t1: { consigne: "Écrire un message à un(e) ami(e) pour raconter son week-end à la campagne en détaillant les événements qui se sont déroulés." },
      t2: { consigne: "Rédiger un message à la direction pour informer qu'un lieu a été trouvé pour la fête de fin d'année, en précisant le lieu, les tarifs, les services et autres informations pertinentes." },
      t3: { titre: "Utilisation des nouvelles technologies dans les écoles : pour ou contre ?", doc1: "Adam : Je suis persuadé que l'intégration des nouvelles technologies dans les écoles est essentielle pour préparer les élèves à l'avenir numérique. L'utilisation des tablettes et ordinateurs motive les élèves et enrichit leur expérience d'apprentissage en leur donnant accès à diverses ressources, favorisant ainsi leur créativité et leur autonomie.", doc2: "Inès : Je reste dubitative face à l'utilisation excessive des technologies dans l'éducation. Cela peut limiter les interactions humaines et entraîner une dépendance aux écrans. À mon avis, les méthodes traditionnelles et le contact direct entre enseignants et élèves sont essentiels pour un développement équilibré des compétences des jeunes." }
    },
    {
      num: 5,
      t1: { consigne: "Dans le cadre d'un reportage sur les activités sportives amateurs, France Télévisions souhaite recueillir des témoignages. Et vous, quelle place occupe le sport dans votre vie ? Envoyez votre témoignage sur francetelevision.fr." },
      t2: { consigne: "Vous avez séjourné dans une magnifique région de votre pays pendant vos vacances. Vous rédigez un message à vos amis dans lequel vous racontez votre séjour et les raisons pour lesquelles cette expérience vous a beaucoup plu." },
      t3: { titre: "École privée : quels enjeux ?", doc1: "En France, les écoles privées ont accueilli un nombre plus important d'élèves lors de la dernière rentrée. Leur popularité n'est pas uniquement due aux résultats obtenus par les élèves. C'est surtout leur réputation qui attire les familles. De nombreux parents considèrent que l'encadrement y est meilleur, que les élèves sont davantage surveillés et que les enseignants sont plus impliqués. Ils sont aussi rassurés par la composition des classes, souvent constituées d'élèves provenant de milieux favorisés. Cela s'explique notamment par le coût des études dans ces établissements, alors que l'enseignement public est gratuit.", doc2: "Les collèges privés accueillent peu d'élèves provenant de milieux défavorisés. Les frais de scolarité représentent un obstacle pour une partie de la population. Cette distinction entre écoles publiques et privées limite la diversité sociale au sein des établissements. Ainsi, les jeunes scolarisés dans le privé ont peu de contacts avec des élèves ayant des conditions de vie différentes. Ce système tend à reproduire les inégalités existantes et à renforcer le sentiment d'être mis à l'écart chez certains jeunes." }
    }
  ],
  "mai-2026": [
    {
      num: 1,
      t1: { consigne: "Rédigez un courriel en réponse à une annonce de recherche de vélo. Présentez votre vélo, décrivez son état, proposez un prix et fixez un rendez-vous pour un essai." },
      t2: { consigne: "Rédigez un message sur un forum pour partager votre expérience d'une journée à la campagne avec vos amis. Décrivez les moments marquants, les activités réalisées et ce que vous avez particulièrement apprécié." },
      t3: { titre: "La sévérité des parents envers les enfants", doc1: "À 22 ans, je vis toujours chez mes parents, qui restent très stricts avec moi malgré mon âge. Plus jeune, il m'était interdit de dormir à l'extérieur ou de rentrer après 21h. Aujourd'hui, bien que je puisse sortir plus tard, ma mère m'appelle sans cesse jusqu'à mon retour à la maison.", doc2: "Certains parents hésitent à être trop stricts, de peur que cela freine l'épanouissement et la personnalité de leurs enfants. Toutefois, céder à toutes leurs demandes peut avoir des conséquences négatives à l'âge adulte. Vivre en société implique le respect de certaines règles essentielles." }
    },
    {
      num: 2,
      t1: { consigne: "Vous souhaitez organiser un week-end avec vos proches le mois prochain. Vous envoyez un message pour leur expliquer votre plan, en décrivant le lieu, le moyen de transport et les activités prévues." },
      t2: { consigne: "COURRIER DES LECTEURS\nPartir un an à l'étranger et tout quitter : est-ce une bonne ou une mauvaise idée ?\nExprimez votre opinion sur le site voyage.internaute.fr avec des exemples tirés de votre expérience personnelle." },
      t3: { titre: "Le rôle du travail", doc1: "Le travail occupe une place importante dans notre vie : dès l'enfance, on nous demande : « Que veux-tu devenir plus tard ? ». Même s'il peut apporter de la satisfaction, il est souvent source de fatigue et peut donner l'impression d'être coincé dans une routine. Aujourd'hui, beaucoup de personnes constatent un déséquilibre entre leur vie professionnelle et leur vie personnelle. Il devient nécessaire de réfléchir à la place du travail dans notre société. Certains pensent qu'en travaillant moins, on pourrait profiter de davantage de temps libre, être plus heureux et mieux vivre.", doc2: "Le travail fait partie de notre identité sociale. Lorsqu'on rencontre quelqu'un pour la première fois, on demande souvent : « Que faites-vous dans la vie ? », ce qui montre l'importance du travail dans la perception de soi. Selon le spécialiste Jean-Daniel Remond, la vie professionnelle contribue à se construire : elle permet de rencontrer des gens, de créer des réseaux personnels et professionnels, de se sentir utile et même de se faire des amis. Même si certains décident de quitter leur emploi, pour la plupart, travailler est essentiel pour exister. Le travail reste donc crucial pour l'équilibre personnel et collectif." }
    },
    {
      num: 3,
      t1: { consigne: "Vous préparez la célébration de votre anniversaire. Vous écrivez à vos amis pour les inviter. Vous leur présentez le déroulement de la soirée et leur demandez de participer à l'organisation." },
      t2: { consigne: "Vous avez pris part à une compétition culinaire. Sur votre site web, vous rédigez un petit article pour décrire le déroulement de la journée. Vous précisez les raisons pour lesquelles cette expérience vous a plu ou non." },
      t3: { titre: "Étudiants et travail saisonnier", doc1: "Après une longue période à l'université, les vacances permettent aux jeunes de se détendre. Ils partent en voyage et profitent de l'été. Pourtant, certains étudiants préfèrent travailler au lieu de partir en vacances : garde d'enfants, service en restauration ou cueillette de fruits. Bien que ces emplois saisonniers aient des points positifs, ils limitent le temps libre des jeunes, qui manquent de repos, de loisirs et de moments en famille ou entre amis. De plus, ces travaux sont parfois difficiles, ennuyeux ou mal payés.", doc2: "Pour quelles raisons de nombreux étudiants travaillent-ils durant les vacances ? Cette expérience représente souvent une entrée dans la vie professionnelle : elle leur permet de développer le sens des responsabilités et de connaître un métier. Gagner de l'argent est aussi motivant. Certains étudiants travaillent pour ne plus dépendre financièrement de leurs parents et pour financer des loisirs ou des voyages. Pour d'autres, travailler l'été est indispensable pour payer les frais d'études ou le loyer." }
    },
    {
      num: 4,
      t1: { consigne: "Votre ami Cédric ne connaît pas le Château de Chombony, où aura lieu votre mariage. Décrivez-lui ce lieu en précisant son emplacement, ses caractéristiques et les moyens de transport pour s'y rendre." },
      t2: { consigne: "Partagez votre expérience d'apprentissage d'une langue étrangère sur un forum en ligne, en évoquant les difficultés rencontrées, les progrès réalisés et les stratégies qui vous ont aidé." },
      t3: { titre: "Cuisinier amateur ou cuisinier professionnel ?", doc1: "Réussir des recettes ne suffit pas pour être un véritable cuisinier. Une formation et une expérience approfondie sont essentielles pour maîtriser les techniques du métier.", doc2: "Certains passionnés de cuisine se forment grâce à internet et deviennent populaires sur les réseaux sociaux. L'histoire d'une amatrice devenue chef et auteure de livres de cuisine illustre ce parcours." }
    },
    {
      num: 5,
      t1: { consigne: "Vous avez vu une annonce en ligne offrant de l'aide aux personnes qui veulent apprendre le français, en les mettant en contact avec des partenaires pour pratiquer et améliorer leur niveau. Vous rédigez un courriel pour répondre, en vous présentant et en disant pourquoi vous voulez pratiquer le français." },
      t2: { consigne: "Vous avez assisté à une fête de famille. Vous envoyez un message à vos amis pour leur parler de cette fête et expliquer ce que vous avez préféré." },
      t3: { titre: "Villes sans voitures : avantages et précautions", doc1: "En raison de la pollution importante observée dans de nombreuses régions, certaines villes ont choisi d'interdire les voitures dans les zones urbaines. La ville d'Oslo, en Norvège, a appliqué cette mesure récemment et constate des effets positifs pour tous. Avec le temps, les accidents diminuent, la dépendance au pétrole est réduite et l'air devient plus sain.", doc2: "Beaucoup de villes lancent des projets visant à interdire la circulation automobile en centre-ville sans préparer les infrastructures indispensables. Certes, diminuer le trafic permettrait de réduire les bouchons, le stress et la pollution de l'air. Mais il est également important de prévoir de grands parkings, de renforcer les transports publics, et de donner des autorisations particulières à certains professionnels, comme les services d'urgence, la police ou les livreurs." }
    },
    {
      num: 6,
      t1: { consigne: "« Je souhaite acheter un vélo en bon état à un prix abordable. Contactez-moi par mail : [email protected] »\nVous possédez un vélo à vendre. Vous rédigez un courriel pour présenter votre vélo et proposer votre prix. Vous fixez aussi un moment pour que l'acheteur puisse le tester." },
      t2: { consigne: "Vous rédigez un message à vos amis pour partager votre expérience d'emploi saisonnier réalisé pendant les vacances d'été." },
      t3: { titre: "Transports en commun : bénéfices et contraintes", doc1: "La gratuité des transports en commun est une initiative très positive. Elle permet de réduire le trafic automobile et de limiter les bouchons. Elle contribue aussi à diminuer la pollution et les risques pour la santé liés à l'air. Dans ma ville, où les transports sont gratuits, on constate une hausse de leur utilisation. Cette mesure a également favorisé le commerce local, car les habitants se rendent plus facilement au centre-ville pour leurs achats.", doc2: "À mon avis, cette mesure n'est pas appropriée. D'abord, la gratuité des transports représente un coût élevé pour les villes, et certaines, comme Toulouse, ont d'autres priorités, par exemple l'aménagement des espaces verts. Ensuite, il vaudrait mieux améliorer la desserte des transports publics plutôt que de les rendre gratuits, car certains quartiers en sont mal équipés. Enfin, garder les transports payants encourage les usagers à mieux respecter les installations, puisqu'ils financent leur fonctionnement." }
    },
    {
      num: 7,
      t1: { consigne: "Rédigez un message afin de convier vos amis à une célébration de fin d'année." },
      t2: { consigne: "Vous avez effectué un séjour au Canada grâce à une agence de voyages. Rédigez un commentaire pour décrire l'expérience que vous avez vécue pendant ce voyage." },
      t3: { titre: "L'interdiction des voitures en ville", doc1: "Face à des niveaux de pollution très élevés observés dans plusieurs régions du monde, certaines villes ont décidé d'interdire la circulation des voitures dans les centres urbains. La capitale norvégienne, Oslo, a récemment choisi cette mesure et en tire un bilan positif, estimant qu'elle profite à tous. Avec le temps, les accidents diminueront, la consommation de pétrole reculera et la qualité de l'air s'améliorera.", doc2: "De nombreuses villes lancent des projets visant à interdire les voitures en milieu urbain sans disposer des moyens et des infrastructures indispensables pour assurer la réussite de ce changement. Certes, la réduction du nombre de voitures permet de diminuer la pollution, mais en contrepartie, il est nécessaire de prévoir de grands parkings, de développer davantage les transports en commun (métros et bus) et d'accorder des autorisations spéciales à certains professionnels (police, services d'urgence, livreurs, etc.)." }
    },
    {
      num: 8,
      t1: { consigne: "Vous souhaitez organiser une fête et souhaitez inviter vos amis tout en leur demandant un coup de main pour la préparation (lieu, date, thème, etc.). Rédigez un message en ce sens." },
      t2: { consigne: "Vous avez participé à une compétition sportive et souhaitez partager votre expérience sur un site internet. Décrivez le déroulement de l'événement (lieu, date, organisation) et donnez votre avis sur votre participation." },
      t3: { titre: "Les menus sans viande dans les cantines scolaires", doc1: "De plus en plus d'établissements scolaires intègrent des repas sans viande dans leurs menus, au moins deux fois par semaine. Certaines études ont démontré que les enfants consomment une quantité excessive de protéines animales. Pour des raisons de santé, les écoles privilégient des alternatives comme le soja, les céréales et les légumes, qui sont plus sains et bénéfiques pour la croissance des enfants. En outre, ces repas sont souvent plus économiques pour les familles. Cette mesure est généralement bien accueillie par les parents et les élèves.", doc2: "La suppression de la viande dans les menus scolaires ne fait pas l'unanimité. Pour certaines familles en difficulté, la cantine représente la seule opportunité pour leurs enfants de consommer de la viande, qui reste un aliment coûteux. Par ailleurs, les producteurs locaux de viande sont affectés économiquement par cette mesure. Enfin, bon nombre d'enfants préfèrent encore les plats à base de viande, trouvant que les steaks de soja manquent de saveur." }
    },
    {
      num: 9,
      t1: { consigne: "Votre ami(e) veut visiter la région où vous vivez. Écrivez-lui un message pour lui proposer quelques lieux intéressants à découvrir." },
      t2: { consigne: "Vous avez assisté récemment à un cours de sport dans une salle de votre ville. Écrivez un article sur votre blog afin de partager votre expérience et donner votre opinion sur cette salle." },
      t3: { titre: "Repas livrés au bureau : avantages et limites", doc1: "Se faire livrer un repas au bureau est un moyen pratique de gagner du temps. On n'a pas besoin de sortir pendant la pause déjeuner, ce qui aide à finir le travail plus tôt. Chacun peut également choisir le repas qu'il souhaite, selon ses envies. Enfin, ce service est accessible à toute heure grâce à des restaurants ouverts en continu.", doc2: "Néanmoins, ce système présente des limites. En cas de nombreuses commandes, les livreurs peuvent être débordés, ce qui cause des retards et du stress. Pour vous, rester assis sans prendre une vraie pause peut fatiguer. Il est donc conseillé de faire une coupure, même brève, afin de rester performant." }
    },
    {
      num: 10,
      t1: { consigne: "Envoyez un courriel à vos amis pour les inviter à fêter votre anniversaire dans un restaurant. Incluez toutes les informations nécessaires comme le lieu, la date, le menu, les prix, et demandez-leur de confirmer leur présence." },
      t2: { consigne: "Sur votre blog, expliquez les raisons qui vous ont poussé à quitter la ville pour vous installer à la campagne. Présentez les avantages de votre nouvelle vie rurale." },
      t3: { titre: "Caméras de surveillance à l'école : pour ou contre ?", doc1: "À l'école où je travaille à Montréal, les caméras de surveillance sont largement présentes. Leur objectif est de dissuader les élèves de commettre des actes de violence. Les enseignants, les parents et la majorité des élèves les accueillent favorablement, car cela renforce la sécurité des enfants et crée un environnement propice à l'enseignement. Cependant, certains élèves expriment des préoccupations quant à leur vie privée.", doc2: "Je m'oppose à l'installation des caméras de surveillance dans nos écoles à Montréal. Les résultats obtenus dans d'autres pays utilisant ce système ne sont pas convaincants. Les individus mal intentionnés peuvent facilement contourner ces caméras très visibles. Pour résoudre les problèmes de discipline à l'école, il est préférable d'améliorer la communication entre enseignants, administration et élèves, et de faire respecter les règles scolaires par tous, plutôt que de dépendre des caméras." }
    },
    {
      num: 11,
      t1: { consigne: "Écrire un message à un(e) ami(e) pour raconter son week-end à la campagne en détaillant les événements qui se sont déroulés." },
      t2: { consigne: "Rédiger un message à la direction pour informer qu'un lieu a été trouvé pour la fête de fin d'année, en précisant le lieu, les tarifs, les services et autres informations pertinentes." },
      t3: { titre: "Utilisation des nouvelles technologies dans les écoles : pour ou contre ?", doc1: "Adam : Je suis persuadé que l'intégration des nouvelles technologies dans les écoles est essentielle pour préparer les élèves à l'avenir numérique. L'utilisation des tablettes et ordinateurs motive les élèves et enrichit leur expérience d'apprentissage en leur donnant accès à diverses ressources, favorisant ainsi leur créativité et leur autonomie.", doc2: "Inès : Je reste dubitative face à l'utilisation excessive des technologies dans l'éducation. Cela peut limiter les interactions humaines et entraîner une dépendance aux écrans. À mon avis, les méthodes traditionnelles et le contact direct entre enseignants et élèves sont essentiels pour un développement équilibré des compétences des jeunes." }
    }
  ],
  "avril-2026": [
    {
      num: 1,
      t1: { consigne: "Vous souhaitez organiser un week-end avec vos proches le mois prochain. Vous envoyez un message pour leur expliquer votre plan, en décrivant le lieu, le moyen de transport et les activités prévues." },
      t2: { consigne: "COURRIER DES LECTEURS\nPartir un an à l'étranger et tout quitter : est-ce une bonne ou une mauvaise idée ?\nExprimez votre opinion sur le site voyage.internaute.fr avec des exemples tirés de votre expérience personnelle." },
      t3: { titre: "Le rôle du travail", doc1: "Le travail occupe une place importante dans notre vie : dès l'enfance, on nous demande : « Que veux-tu devenir plus tard ? ». Même s'il peut apporter de la satisfaction, il est souvent source de fatigue et peut donner l'impression d'être coincé dans une routine. Aujourd'hui, beaucoup de personnes constatent un déséquilibre entre leur vie professionnelle et leur vie personnelle. Il devient nécessaire de réfléchir à la place du travail dans notre société. Certains pensent qu'en travaillant moins, on pourrait profiter de davantage de temps libre, être plus heureux et mieux vivre.", doc2: "Le travail fait partie de notre identité sociale. Lorsqu'on rencontre quelqu'un pour la première fois, on demande souvent : « Que faites-vous dans la vie ? », ce qui montre l'importance du travail dans la perception de soi. Selon le spécialiste Jean-Daniel Remond, la vie professionnelle contribue à se construire : elle permet de rencontrer des gens, de créer des réseaux personnels et professionnels, de se sentir utile et même de se faire des amis. Même si certains décident de quitter leur emploi, pour la plupart, travailler est essentiel pour exister. Le travail reste donc crucial pour l'équilibre personnel et collectif." }
    },
    {
      num: 2,
      t1: { consigne: "« Bonjour, Je souhaite commencer le sport dans une salle. Est-ce que tu pourrais me donner des informations sur les salles de sport près de chez nous ? Merci d'avance. Bisous, Laura. »\nVous écrivez une réponse à Laura dans laquelle vous décrivez une salle de sport que vous connaissez et vous précisez les renseignements utiles (lieu, types de cours, prix, etc.)." },
      t2: { consigne: "Un concours en ligne invite les participants à raconter leur plus belle fête. Vous participez à ce concours. Dans votre texte, vous racontez comment cette fête s'est déroulée (anniversaire, fête culturelle, etc.) et vous précisez ce que vous en retenez." },
      t3: { titre: "Lecture et enfants : encourager sans forcer", doc1: "Obliger les enfants à lire n'est pas une bonne solution. Lire est une pratique particulière. Quand un enfant aime le sport, on ne le contraint pas, on essaie de le motiver. Il en va de même pour la lecture, selon Laurence T., pédopsychiatre et experte de l'enfance. Elle affirme que « l'amour de la lecture ne peut pas être imposé ».", doc2: "Lire avec ses enfants est une activité agréable et bénéfique. Elle contribue au développement des enfants, car une lecture régulière leur permet d'apprendre de nouveaux mots. Elle les aide également à mieux écouter et à se familiariser avec les mots écrits. Ce moment est idéal pour partager du plaisir en famille, de manière détendue et ludique. Les parents doivent essayer de lire des histoires à leurs enfants dès leur jeune âge, même après une journée fatigante. Cinq à dix minutes par jour sont suffisantes pour leur donner le goût de la lecture durablement." }
    },
    {
      num: 3,
      t1: { consigne: "Rédigez un message destiné à vos amis afin de les convier à votre anniversaire et de leur présenter le programme de la fête." },
      t2: { consigne: "Donnez votre avis en commentaire sous une publication Facebook concernant les études à l'étranger en mentionnant les points positifs et négatifs de cette expérience." },
      t3: { titre: "Technologie et enfants", doc1: "Les élèves du primaire ont la possibilité d'utiliser la technologie pour chercher des vidéos liées à leurs leçons étudiés en classe ou pour s'exercer avec des jeux qui développent leurs compétences en mathématiques, en lecture et en saisie au clavier.", doc2: "Aujourd'hui, les technologies poussent les enfants à rester inactifs, ce qui inquiète beaucoup les parents. Cela limite les jeux créatifs, les échanges sociaux directs et l'activité physique. Pourquoi ne pas encourager vos enfants à poser leurs appareils en essayant des activités ludiques ?" }
    },
    {
      num: 4,
      t1: { consigne: "Votre ami(e) veut visiter la région où vous vivez. Écrivez-lui un message pour lui proposer quelques lieux intéressants à découvrir." },
      t2: { consigne: "Vous avez assisté récemment à un cours de sport dans une salle de votre ville. Écrivez un article sur votre blog afin de partager votre expérience et donner votre opinion sur cette salle." },
      t3: { titre: "Repas livrés au bureau : avantages et limites", doc1: "Se faire livrer un repas au bureau est un moyen pratique de gagner du temps. On n'a pas besoin de sortir pendant la pause déjeuner, ce qui aide à finir le travail plus tôt. Chacun peut également choisir le repas qu'il souhaite, selon ses envies. Enfin, ce service est accessible à toute heure grâce à des restaurants ouverts en continu.", doc2: "Néanmoins, ce système présente des limites. En cas de nombreuses commandes, les livreurs peuvent être débordés, ce qui cause des retards et du stress. Pour vous, rester assis sans prendre une vraie pause peut fatiguer. Il est donc conseillé de faire une coupure, même brève, afin de rester performant." }
    },
    {
      num: 5,
      t1: { consigne: "Vous prévoyez de vous déménager à Nice. Vous envoyez un message à une agence immobilière afin de trouver un appartement. Précisez vos besoins (surface, budget, nombre de pièces, quartier, etc.)." },
      t2: { consigne: "Vous avez récemment entamé des cours dans une école de langues. Rédigez un message à vos amis pour leur parler de votre première semaine et partager vos impressions sur les cours, les enseignants et l'atmosphère." },
      t3: { titre: "Caméras de surveillance : sécurité ou limites ?", doc1: "De nos jours, les caméras de surveillance se multiplient dans les villes. Elles sont appréciées par de nombreux Français, car elles apportent plus de sécurité. Selon une enquête, 75 % des personnes sont pour leur utilisation. La majorité accepte d'être filmée dans les espaces publics, mais pas dans les entreprises.", doc2: "Selon certaines recherches, la vidéosurveillance est onéreuse et peu performante. Les caméras sont souvent repérées, ce qui limite leur efficacité contre les infractions comme le vol ou la violence. En plus, leur utilisation demande des ressources humaines importantes. Une étude en Allemagne montre qu'il faut jusqu'à sept personnes pour surveiller une seule caméra." }
    },
    {
      num: 6,
      t1: { consigne: "« Bonjour,\nOn m'a dit que tu t'es inscrit dans une salle de sport intéressante.\nPeux-tu m'en dire plus ? »\nVous lui répondez en décrivant cette salle (ambiance, matériel, prix, etc.)." },
      t2: { consigne: "Vous avez consulté une discussion sur Internet à propos des formations en ligne. Rédigez un message pour partager votre expérience personnelle (cours de langue, formation professionnelle, etc.) et exprimer ce que vous avez aimé et moins apprécié." },
      t3: { titre: "Les produits faits maison : pour ou contre ?", doc1: "Fabriquer vos propres produits biologiques à la maison offre un contrôle total sur les ingrédients, garantissant des options plus saines et personnalisées. Cela contribue également à réduire les déchets plastiques grâce à des emballages réutilisables. De plus, vous économiserez de l'argent à long terme et développerez des compétences créatives, favorisant ainsi un mode de vie plus durable.", doc2: "Cependant, la fabrication de produits biologiques à domicile comporte des risques. Les erreurs de formulation peuvent entraîner des produits inefficaces ou irritants. De plus, le temps et les efforts nécessaires pour trouver et préparer les ingrédients peuvent être contraignants. Il y a également un manque de garantie de sécurité et de stabilité des produits faits maison, avec un risque accru de contamination bactérienne si les produits ne sont pas correctement conservés." }
    },
    {
      num: 7,
      t1: { consigne: "Invitez votre ami(e) à venir passer les vacances chez vous. Dans votre message, décrivez les sites touristiques et les endroits intéressants à découvrir dans votre ville." },
      t2: { consigne: "Vous avez été sélectionné(e) pour un concours où le prix est un séjour de deux semaines dans votre ville favorite. Le thème du concours était \"Mon artiste préféré\". Rédigez un article de blog pour parler de l'artiste que vous aimez le plus." },
      t3: { titre: "Chasse aux animaux : une pratique à soutenir ou à rejeter ?", doc1: "Sophie (28 ans) : « Je fais partie de ceux qui ne parviennent pas à comprendre comment on peut prendre plaisir à tuer des animaux. Je fais aussi partie de ceux qui ne saisissent pas comment on peut prétendre aimer la nature tout en contribuant à sa destruction. »", doc2: "Bernard (Journaliste de la FRM) : « La chasse est pratiquée pour diverses raisons : qu'il s'agisse de se nourrir, de commercer, de gérer la faune, de protéger la propriété, de faire de l'exercice, de se divertir ou de chercher du prestige. »" }
    },
    {
      num: 8,
      t1: { consigne: "Rédiger un message en réponse à un ami qui demande des informations sur une salle de sport réputée pour sa qualité." },
      t2: { consigne: "Rédiger un message décrivant une expérience avec les formations en ligne, en mettant en avant les points positifs et les éventuels défis rencontrés." },
      t3: { titre: "Produits faits maison : avantages et limites", doc1: "Produire ses propres produits biologiques à domicile permet de maîtriser entièrement les ingrédients utilisés, offrant ainsi des alternatives plus saines et adaptées aux besoins individuels. Cela participe également à la réduction des déchets plastiques grâce à l'utilisation d'emballages réutilisables. De plus, cette démarche permet de réaliser des économies sur le long terme tout en développant des compétences créatives, favorisant un mode de vie plus durable.", doc2: "La fabrication de produits biologiques à domicile présente certains défis. Des erreurs dans la formulation peuvent affecter leur efficacité ou provoquer des irritations. Le temps et les efforts nécessaires pour sélectionner et préparer les ingrédients peuvent également représenter une contrainte. De plus, l'absence de garantie sur la sécurité et la stabilité des produits maison augmente le risque de contamination si les règles de conservation ne sont pas respectées." }
    },
    {
      num: 9,
      t1: { consigne: "Rédigez un courriel en réponse à une annonce de recherche de vélo. Présentez votre vélo, décrivez son état, proposez un prix et fixez un rendez-vous pour un essai." },
      t2: { consigne: "Rédigez un message sur un forum pour partager votre expérience d'une journée à la campagne avec vos amis. Décrivez les moments marquants, les activités réalisées et ce que vous avez particulièrement apprécié." },
      t3: { titre: "La sévérité des parents envers les enfants", doc1: "À 22 ans, je vis toujours chez mes parents, qui restent très stricts avec moi malgré mon âge. Plus jeune, il m'était interdit de dormir à l'extérieur ou de rentrer après 21h. Aujourd'hui, bien que je puisse sortir plus tard, ma mère m'appelle sans cesse jusqu'à mon retour à la maison.", doc2: "Certains parents hésitent à être trop stricts, de peur que cela freine l'épanouissement et la personnalité de leurs enfants. Toutefois, céder à toutes leurs demandes peut avoir des conséquences négatives à l'âge adulte. Vivre en société implique le respect de certaines règles essentielles." }
    },
    {
      num: 10,
      t1: { consigne: "Envoyez un courriel à vos amis pour les inviter à fêter votre anniversaire dans un restaurant. Incluez toutes les informations nécessaires comme le lieu, la date, le menu, les prix, et demandez-leur de confirmer leur présence." },
      t2: { consigne: "Sur votre blog, expliquez les raisons qui vous ont poussé à quitter la ville pour vous installer à la campagne. Présentez les avantages de votre nouvelle vie rurale." },
      t3: { titre: "Caméras de surveillance à l'école : pour ou contre ?", doc1: "À l'école où je travaille à Montréal, les caméras de surveillance sont largement présentes. Leur objectif est de dissuader les élèves de commettre des actes de violence. Les enseignants, les parents et la majorité des élèves les accueillent favorablement, car cela renforce la sécurité des enfants et crée un environnement propice à l'enseignement. Cependant, certains élèves expriment des préoccupations quant à leur vie privée.", doc2: "Je m'oppose à l'installation des caméras de surveillance dans nos écoles à Montréal. Les résultats obtenus dans d'autres pays utilisant ce système ne sont pas convaincants. Les individus mal intentionnés peuvent facilement contourner ces caméras très visibles. Pour résoudre les problèmes de discipline à l'école, il est préférable d'améliorer la communication entre enseignants, administration et élèves, et de faire respecter les règles scolaires par tous, plutôt que de dépendre des caméras." }
    },
    {
      num: 11,
      t1: { consigne: "Écrire un message à un(e) ami(e) pour raconter son week-end à la campagne en détaillant les événements qui se sont déroulés." },
      t2: { consigne: "Rédiger un message à la direction pour informer qu'un lieu a été trouvé pour la fête de fin d'année, en précisant le lieu, les tarifs, les services et autres informations pertinentes." },
      t3: { titre: "Utilisation des nouvelles technologies dans les écoles : pour ou contre ?", doc1: "Adam : Je suis persuadé que l'intégration des nouvelles technologies dans les écoles est essentielle pour préparer les élèves à l'avenir numérique. L'utilisation des tablettes et ordinateurs motive les élèves et enrichit leur expérience d'apprentissage en leur donnant accès à diverses ressources, favorisant ainsi leur créativité et leur autonomie.", doc2: "Inès : Je reste dubitative face à l'utilisation excessive des technologies dans l'éducation. Cela peut limiter les interactions humaines et entraîner une dépendance aux écrans. À mon avis, les méthodes traditionnelles et le contact direct entre enseignants et élèves sont essentiels pour un développement équilibré des compétences des jeunes." }
    }
  ]
};

// Export for use in other files
if (typeof module !== 'undefined' && module.exports) {
  module.exports = { DEFAULT_SUBJECT_BANK };
}
